### ISSUE TITLE
Issue about interacting with matlab

### ISSUE THREAD

**Issue by callmebigbig** [artisynth/artisynth_core#15]
When interacting with matlab, once -help is entered, a [] is returned, and you cannot quit() the current command and call artisynth for subsequent simulation unless matlab is restarted.

**Comment by JohnLloyd7** [comment]
Thanks for the feedback! The default command line argument settings used by ArtiSynth are defined statically, and because restarting ArtiSynth in MATLAB does not cause classes to be reloaded, these settings were persisting from the previous start. This has been fixed by explicitly reinitializing the static variables.
